### ISSUE TITLE
Page does not redirect and console.log not appearing

### ISSUE THREAD

**Issue by Mepkaz01** [Mepkaz01/Project3-frontend.github.io#1]
Under Profile component, user edit and delete are working however when console.log is not appearing after function is done. Page is not redirecting after delete to home page. After delete the page stays in the /profile/:id page instead of redirecting to home page ('/'). Looked up the issue and found maybe adding setState after api link or changing the function completely. The code half works so I don't want to change the working part. 

https://stackoverflow.com/questions/57832065/react-delete-record-and-redirect-user-to-dashboard-page-with-updated-state

![image](https://user-images.githubusercontent.com/82845234/122330889-f4911d80-cf01-11eb-9086-92f5003d1984.png)

**Comment by davidmagbee** [comment]
Patricia, not sure exactly which `console.log` you're referring to, as there are five in this code snippet. Keep  in mind that the `console.log` in the methods will only be called when those methods are called. 

Are you receiving any errors when using your declarative routing to the deleted `id` page? If so, please share those as that will be helpful in determining exactly what is happening. I'm also seeing you use `history` but I do not see `history` in state anywhere. 

 I'm also dropping some additional resources for you to dig into in the meantime:
- Have you taken a look at the [docs for history](https://github.com/ReactTraining/history/tree/master/docs)? 
- [Using declarative routing with `history` in React Router](https://reactrouter.com/web/api/history)
- [This is older, but could possibly shed some light for you as well](https://stackoverflow.com/questions/44312437/react-router-v4-this-props-history-push-not-working)

Some alternatives methods for `Redirect`:
- [React Router: Redirect](https://reactrouter.com/web/api/Redirect)

**Comment by Mepkaz01** [comment]
I got it fixed thank you!
